### ISSUE TITLE
upgrade.sh的Diy_Part3建议

### ISSUE THREAD

**Issue by ghost** [281677160/common#1]
upgrade.sh的Diy_Part3部分
第127行[[ -n ${Legacy_Firmware} ]] && {是不是可以改成[[ -e ${Legacy_Firmware} ]] && {
目前存在问题是：如果只选择EFI模式引导的固件编译，会造成“build-openwrt的- name: 把定时更新固件发布到云端1”出错，提示
md5sum: openwrt-x86-64-generic-squashfs-combined.img.gz: No such file or directory
sha256sum: openwrt-x86-64-generic-squashfs-combined.img.gz: No such file or directory
cp: cannot stat 'openwrt-x86-64-generic-squashfs-combined.img.gz': No such file or directory
类似的有133、145行

**Comment by 281677160** [comment]
谢谢提醒，我有空的时候去看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/common"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月11日(星期六) 晚上6:53
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[281677160/common] upgrade.sh的Diy_Part3建议 (#1)





 
upgrade.sh的Diy_Part3部分
 第127行[[ -n ${Legacy_Firmware} ]] &amp;&amp; {是不是可以改成[[ -e ${Legacy_Firmware} ]] &amp;&amp; {
 目前存在问题是：如果只选择EFI模式引导的固件编译，会造成“build-openwrt的- name: 把定时更新固件发布到云端1”出错，提示
 md5sum: openwrt-x86-64-generic-squashfs-combined.img.gz: No such file or directory
 sha256sum: openwrt-x86-64-generic-squashfs-combined.img.gz: No such file or directory
 cp: cannot stat 'openwrt-x86-64-generic-squashfs-combined.img.gz': No such file or directory
 类似的有133、145行
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ghost** [comment]
辛苦大佬了，为大家提供了这么好的资源

**Comment by 281677160** [comment]
改好了，以后发现有什么问题，欢迎提出

**Comment by 281677160** [comment]
> 辛苦大佬了，为大家提供了这么好的资源

呵呵，你客气了，那有什么好资源啊，就是源码作者的基础上加点插件，加个定时更新固件，减少一点点坑，就这样而已
